# Hii_202107_coupled_test4 — WIS BC + 中川・八戸川のみ全開 + LFP + ポンプ + 連成

event_name: Hii_202107_coupled_test4

result_dir: ../03_Result/Hii_202107_coupled_test4
waterlevel_csv: timeseries_of_waterlevel_river1dh.csv
discharge_csv: timeseries_of_discharge_river1dh.csv

wis_output_dir: ../../Download_WIS/output
water_system: 斐伊川

match:
  max_distance_m: 200

output_dir: output/Hii_202107_coupled_test4
