# combo_777 — 木次=Riemann(7), 上島=Riemann(7), 新三刀屋=Riemann(7)

event_name: Hii_202107_coupled_shinmitoya_combo_777

result_dir: ../03_Result/Hii_202107_riv_shinmitoya_combo_777
waterlevel_csv: timeseries_of_waterlevel_river1dh.csv
discharge_csv: timeseries_of_discharge_river1dh.csv

wis_output_dir: ../../Download_WIS/output
water_system: 斐伊川

match:
  max_distance_m: 200

output_dir: output/Hii_202107_coupled_shinmitoya_combo_777
